modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="loconautics"
version="${mod_version}"
displayName="Loconautics"
authors="Lycoris, MDLOP"
description='''
A simple mod that makes the Create trains work with the Sable engine
'''

[[mixins]]
config="loconautics.mixins.json"

[[dependencies.loconautics]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.loconautics]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.loconautics]]
modId="create"
type="required"
versionRange="[0.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.loconautics]]
modId="sable"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.loconautics]]
modId="aeronautics"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"